language: cpp
compiler:
  - gcc
  - clang

sudo: enabled
dist: trusty

before_install:
  - mkdir sdl2install
  - wget https://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar xf SDL2-2.0.0.tar.gz
  - cd SDL2-2.0.0
  - ./configure
  - make
  - sudo make install
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - cmake --build .