language: cpp
compiler:
  - gcc
  - clang

sudo: enabled
dist: precise

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - cmake --build .