language: cpp
compiler:
  - gcc
  - clang

sudo: enabled
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsdl2-2.0
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - cmake --build .