language: cpp

sudo: enabled
dist: trusty

os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install ssh 
  - sudo apt-get install mercurial
  - hg clone https://hg.libsdl.org/SDL SDL
  - cd SDL
  - mkdir SDLbuild
  - cd SDLbuild
  - ../configure
  - make
  - sudo make install

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .