language: cpp

sudo: enabled
dist: trusty

os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get update
  - sudo apt-get upgrade
  - rpm -ql libsdl2-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .