language: cpp

sudo: enabled
dist: trusty

os: linux

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install ssh 
  - sudo apt-get install mercurial
  - hg clone https://hg.libsdl.org/SDL SDL
  - cd SDL
  - mkdir SDLbuild
  - cd SDLbuild
  - ../configure
  - make
  - sudo make install
  - cd ..
  - cd ..
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .